[package]
name = "actuary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
aws-config = "0.54.1"
rand = "0.8.4"
rand_distr = "0.4.3"
serde = { version = "^1", features = ["derive"] }
tokio = { version = "1.16.1", features = ["full"] }